SystemOrganization addCategory: #'Kinisi-Lab-Tests'!
SystemOrganization addCategory: #'Kinisi-Lab-Tests-Core'!
SystemOrganization addCategory: #'Kinisi-Lab-Tests-ExampleSetting'!
SystemOrganization addCategory: #'Kinisi-Lab-Tests-General'!
SystemOrganization addCategory: #'Kinisi-Lab-Tests-Observation'!
SystemOrganization addCategory: #'Kinisi-Lab-Tests-Simulation'!
SystemOrganization addCategory: #'Kinisi-Lab-Tests-Support'!
