name: Run Kinisi tests
on: [push]
jobs:
 run-smalltakCI:
  runs-on: ${{ matrix.operating-system }}
  strategy:
   fail-fast: false
   matrix:
    operating-system: [ubuntu-latest, macos-latest, windows-latest]
    smalltalk: [Pharo64-8.0, Pharo32-8.0]
    exclude:
     - operating-system: macos-latest
       smalltalk: Pharo32-8.0
  env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  steps:
   - uses: actions/checkout@v2
   - uses: hpi-swa/setup-smalltalkCI@v1
     id: smalltalkci
     with:
      smalltalk-image: ${{ matrix.smalltalk }}
   - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
     shell: bash
     timeout-minutes: 15
